### ISSUE TITLE
Result Whats mean

### ISSUE THREAD

**Issue by MohMehrnia** [SAH-UJA/topsis#2]
Hi,
how dow translate result:
My result for one element is [1, 0.3319243271474708, 2]
and have a 3 part, each part what's mean?
thanks

**Comment by SAH-UJA** [comment]
The result is of the format : [ Sample/tuple number  Topsis Score  Rank ]
The tuple with rank 1 is preferred. Basically this method is used to select the best model when there is no way to decide since there are multiple criterion for decision making like accuracy, F score, sensitivity, rmse, etc. Here we are supposed to minimize rmse which maximizing others. For some samples accuracy will be best and for others sensitivity will be high and so on so which model should we select can be decided using topsis and select that tuple or model or sample with highest rank i.e. 1 or maximum Topsis performance score.

**Comment by SAH-UJA** [comment]
Consider the following case : 
I am supposed to buy a phone. Topsis will help me decide which phone should I buy.

S.No.  Cost  Storage  Looks
   0       2000     8GB     Good
   1       1500     8GB   Excellent 
   2       2500    16GB   Average

Now, i can't make a clear decision as such because if i get max storage my cost will be high and i have to compromise with looks and if i want good looking phone i have to compromise with storage. So i can decide weights based on my priorities and impact values based on what feature i want to maximize(+) or minimize(-). I will select that phone that gives me best performance or rank 1 after topsis analysis.

**Comment by SAH-UJA** [comment]
In this case  [1, 0.3319243271474708, 2]
Tuple no. = 1 (i.e. second sample)
Topsis score = 0.3319243271474708
Rank = 2
